name: unidos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.2
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  linux: false
  image_path: "assets/icon/icon.png"